# DB configuration
spring:
# H2
  datasource:
    url: jdbc:h2:tcp://localhost/~/boardMall
    username: sa
    password:
    driver-class-name: org.h2.Driver
## MySQL
#  datasource:
#    url: jdbc:mysql://min-db.ctv5qlni3dke.ap-northeast-2.rds.amazonaws.com:3306/boardmalldb?serverTimezone=UTC&characterEncoding=UTF-8
#    username: admin
#    password: adminadmin
#    driver-class-name: com.mysql.cj.jdbc.Driver


  ## redis configuration
  redis:
#    host: localhost
    host: redis-board.lrih02.ng.0001.apn2.cache.amazonaws.com
    password:
    port: 6379
  session:
    store-type: redis
    timeout: 30000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  messages:
    basename: errors

logging:
  level:
    org.hibernate.SQL: debug

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.dokong.board
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8080/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

